# Generated by Django 5.1.7 on 2025-03-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_created_by_admin_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='medical_licenses/'),
        ),
    ]
