# Generated by Django 5.1.7 on 2025-03-18 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_license_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTechProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_tech_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ward_type', models.CharField(choices=[('GENERAL', 'General Ward'), ('NICU', 'Neonatal Intensive Care Unit'), ('PICU', 'Pediatric Intensive Care Unit'), ('PRIVATE', 'Private Room'), ('ISOLATION', 'Isolation Ward'), ('SURGICAL', 'Surgical Ward')], max_length=20)),
                ('capacity', models.PositiveIntegerField(help_text='Total number of beds in the ward')),
                ('available_beds', models.PositiveIntegerField(help_text='Number of currently available beds')),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_wards', to='api.doctorprofile')),
                ('assigned_nurses', models.ManyToManyField(blank=True, related_name='assigned_wards', to='api.nurseprofile')),
            ],
        ),
    ]
