# Generated by Django 5.1.7 on 2025-03-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_labtechprofile_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='patient_profile_pictures/')),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], max_length=3)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('birth_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('chronic_conditions', models.TextField(blank=True, null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('vaccination_status', models.TextField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=100, null=True)),
                ('school_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_id', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('surgical_history', models.TextField(blank=True, null=True)),
                ('family_medical_history', models.TextField(blank=True, null=True)),
                ('developmental_notes', models.TextField(blank=True, null=True)),
                ('special_needs', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_to_child', to='api.parentprofile')),
            ],
        ),
    ]
