# Generated by Django 5.1.7 on 2025-03-19 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='guardian',
        ),
        migrations.AddField(
            model_name='child',
            name='primary_guardian',
            field=models.ForeignKey(default=106, on_delete=django.db.models.deletion.CASCADE, related_name='primary_children', to='api.parentprofile'),
        ),
        migrations.AddField(
            model_name='child',
            name='relationship_to_primary_guardian',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='relationship_to_secondary_guardian',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='secondary_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_children', to='api.parentprofile'),
        ),
    ]
