# Generated by Django 5.1.7 on 2025-03-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_child_guardian_child_primary_guardian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='current_bmi_interpretation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
