# Generated by Django 5.1.7 on 2025-03-19 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_growthrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='primary_guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_children', to='api.parentprofile'),
        ),
    ]
