# Generated by Django 5.1.7 on 2025-03-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_shift_doctorprofile_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseprofile',
            name='shifts',
            field=models.ManyToManyField(blank=True, related_name='nurses', to='api.shift'),
        ),
    ]
