# Generated by Django 5.1.7 on 2025-03-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_nurseprofile_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtechprofile',
            name='shifts',
            field=models.ManyToManyField(blank=True, related_name='lab_techs', to='api.shift'),
        ),
        migrations.AddField(
            model_name='pharmacistprofile',
            name='shifts',
            field=models.ManyToManyField(blank=True, related_name='pharmacists', to='api.shift'),
        ),
    ]
