# Generated by Django 5.1.7 on 2025-03-21 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_labtechprofile_shifts_pharmacistprofile_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='shifts',
        ),
        migrations.RemoveField(
            model_name='labtechprofile',
            name='shifts',
        ),
        migrations.RemoveField(
            model_name='nurseprofile',
            name='shifts',
        ),
        migrations.RemoveField(
            model_name='pharmacistprofile',
            name='shifts',
        ),
    ]
