# Generated by Django 5.1.7 on 2025-03-21 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_doctorprofile_shifts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='api.doctorprofile')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='api.shift')),
            ],
        ),
        migrations.CreateModel(
            name='LabTechShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lab_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='api.labtechprofile')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tech_assignments', to='api.shift')),
            ],
        ),
        migrations.CreateModel(
            name='NurseShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='api.nurseprofile')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_assignments', to='api.shift')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacistShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='api.pharmacistprofile')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacist_assignments', to='api.shift')),
            ],
        ),
    ]
