# Generated by Django 5.1.7 on 2025-03-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_doctorshiftassignment_assigned_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorshiftassignment',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='labtechshiftassignment',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='nurseshiftassignment',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='pharmacistshiftassignment',
            name='shift',
        ),
        migrations.AddField(
            model_name='doctorshiftassignment',
            name='shifts',
            field=models.ManyToManyField(related_name='doctor_assignments', to='api.shift'),
        ),
        migrations.AddField(
            model_name='labtechshiftassignment',
            name='shifts',
            field=models.ManyToManyField(related_name='lab_tech_assignments', to='api.shift'),
        ),
        migrations.AddField(
            model_name='nurseshiftassignment',
            name='shifts',
            field=models.ManyToManyField(related_name='nurse_assignments', to='api.shift'),
        ),
        migrations.AddField(
            model_name='pharmacistshiftassignment',
            name='shifts',
            field=models.ManyToManyField(related_name='pharmacist_assignments', to='api.shift'),
        ),
    ]
