# Generated by Django 5.1.7 on 2025-03-24 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.parentprofile'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('parent', 'doctor', 'child', 'appointment_date', 'appointment_time'), name='unique_appointment'),
        ),
    ]
