# Generated by Django 5.1.7 on 2025-03-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_appointment_parent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment',
        ),
    ]
