# Generated by Django 5.1.7 on 2025-03-28 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_appointment_unique_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('recommended_age_start', models.PositiveIntegerField(help_text='Recommended start age in months')),
                ('recommended_age_end', models.PositiveIntegerField(help_text='Recommended end age in months')),
                ('doses_required', models.PositiveIntegerField(default=1)),
                ('booster_required', models.BooleanField(blank=True, default=False, null=True)),
                ('booster_interval_months', models.PositiveIntegerField(blank=True, help_text='Number of months after the initial dose for the booster.', null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveIntegerField()),
                ('scheduled_date', models.DateField()),
                ('administered_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('EXEMPTED', 'Exempted')], default='SCHEDULED', max_length=20)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('administered_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['doctor', 'nurse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.child')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vaccine')),
            ],
        ),
    ]
