# Generated by Django 5.1.7 on 2025-03-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_bed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('ward', 'bed_number'), name='unique_bed_in_ward'),
        ),
    ]
