# Generated by Django 5.1.7 on 2025-03-29 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_bed_unique_bed_in_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('admission_reason', models.TextField(blank=True, help_text='Reason for admission', null=True)),
                ('initial_diagnosis', models.TextField(blank=True, help_text='Initial diagnosis upon admission', null=True)),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='api.doctorprofile')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='api.bed')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='api.child')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionVitalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Temperature in Celsius', max_digits=4)),
                ('heart_rate', models.PositiveIntegerField(help_text='Heart rate in beats per minute')),
                ('blood_pressure', models.CharField(help_text="e.g., '120/80'", max_length=20)),
                ('respiratory_rate', models.PositiveIntegerField(help_text='Breaths per minute')),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, help_text='SpO2 percentage (0-100)', null=True)),
                ('head_circumference', models.DecimalField(blank=True, decimal_places=1, help_text='Head circumference in centimeters', max_digits=4, null=True)),
                ('capillary_refill', models.DecimalField(blank=True, decimal_places=1, help_text='Capillary refill time in seconds', max_digits=3, null=True)),
                ('pain_score', models.PositiveIntegerField(blank=True, help_text='Pain score (0-10)', null=True)),
                ('consciousness_level', models.CharField(blank=True, help_text="e.g., 'Alert', 'Verbal', 'Pain', 'Unresponsive' (AVPU scale)", max_length=50, null=True)),
                ('glucose_level', models.DecimalField(blank=True, decimal_places=1, help_text='Blood glucose in mg/dL', max_digits=5, null=True)),
                ('hydration_status', models.CharField(blank=True, help_text="e.g., 'Well hydrated', 'Mild dehydration', 'Moderate dehydration', 'Severe dehydration'", max_length=50, null=True)),
                ('update_child_record', models.BooleanField(default=True, help_text="Update the child's main record with weight/height/BMI if measured")),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional observations or notes about vitals', null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='api.admissionrecord')),
                ('taken_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['doctor', 'nurse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
