# Generated by Django 5.1.7 on 2025-03-29 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_admissionrecord_admissionvitalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionrecord',
            name='discharge_date',
            field=models.DateTimeField(blank=True, help_text='Date when patient is discharged', null=True),
        ),
        migrations.AlterField(
            model_name='admissionrecord',
            name='bed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission', to='api.bed'),
        ),
    ]
