# Generated by Django 5.1.7 on 2025-03-30 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_admissionrecord_discharge_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionrecord',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission', to='api.bed'),
        ),
    ]
