# Generated by Django 5.1.7 on 2025-03-30 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_admissionrecord_bed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionVitalRecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('heart_rate', models.PositiveIntegerField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('respiratory_rate', models.PositiveIntegerField()),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, null=True)),
                ('head_circumference', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('capillary_refill', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('pain_score', models.PositiveIntegerField(blank=True, null=True)),
                ('consciousness_level', models.CharField(blank=True, max_length=50, null=True)),
                ('glucose_level', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('hydration_status', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admission_vital_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.admissionvitalrecord')),
                ('updated_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['doctor', 'nurse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
