# Generated by Django 5.1.7 on 2025-03-30 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_admissionvitalrecordhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionvitalrecord',
            options={},
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='blood_pressure',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='capillary_refill',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='consciousness_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='glucose_level',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='head_circumference',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='heart_rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='hydration_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='oxygen_saturation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='pain_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='respiratory_rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='update_child_record',
            field=models.BooleanField(default=True),
        ),
    ]
