# Generated by Django 5.1.7 on 2025-03-30 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_admissionvitalrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionvitalrecord',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='blood_pressure',
            field=models.CharField(help_text="e.g., '120/80'", max_length=20),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='capillary_refill',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Capillary refill time in seconds', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='consciousness_level',
            field=models.CharField(blank=True, help_text="e.g., 'Alert', 'Verbal', 'Pain', 'Unresponsive' (AVPU scale)", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='glucose_level',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Blood glucose in mg/dL', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='head_circumference',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Head circumference in centimeters', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='heart_rate',
            field=models.PositiveIntegerField(help_text='Heart rate in beats per minute'),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='hydration_status',
            field=models.CharField(blank=True, help_text="e.g., 'Well hydrated', 'Mild dehydration', 'Moderate dehydration', 'Severe dehydration'", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional observations or notes about vitals', null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='oxygen_saturation',
            field=models.PositiveIntegerField(blank=True, help_text='SpO2 percentage (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='pain_score',
            field=models.PositiveIntegerField(blank=True, help_text='Pain score (0-10)', null=True),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='respiratory_rate',
            field=models.PositiveIntegerField(help_text='Breaths per minute'),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='taken_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['doctor', 'nurse']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='temperature',
            field=models.DecimalField(decimal_places=1, help_text='Temperature in Celsius', max_digits=4),
        ),
        migrations.AlterField(
            model_name='admissionvitalrecord',
            name='update_child_record',
            field=models.BooleanField(default=True, help_text="Update the child's main record with weight/height/BMI if measured"),
        ),
    ]
