# Generated by Django 5.1.7 on 2025-04-24 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_systemlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ndc_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='National Drug Code')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=100, null=True)),
                ('route', models.CharField(blank=True, choices=[('PO', 'Oral'), ('IV', 'Intravenous'), ('IM', 'Intramuscular'), ('SC', 'Subcutaneous'), ('TOP', 'Topical'), ('INH', 'Inhalation'), ('REC', 'Rectal'), ('OPH', 'Ophthalmic'), ('OT', 'Otic'), ('NAS', 'Nasal'), ('SL', 'Sublingual')], max_length=3, null=True)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('concentration', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('is_available', models.BooleanField(default=True)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requires_weight_based_dosing', models.BooleanField(default=False)),
                ('minimum_age_months', models.PositiveIntegerField(blank=True, help_text='Minimum age in months', null=True)),
                ('maximum_age_months', models.PositiveIntegerField(blank=True, help_text='Maximum age in months', null=True)),
                ('minimum_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pediatric_notes', models.TextField(blank=True, null=True)),
                ('special_storage', models.CharField(blank=True, max_length=255, null=True)),
                ('controlled_substance', models.BooleanField(default=False)),
                ('controlled_substance_class', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('icd_code', models.CharField(blank=True, help_text='ICD-10 diagnosis code', max_length=10, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('CHRONIC', 'Chronic'), ('RECURRENT', 'Recurrent'), ('PROVISIONAL', 'Provisional'), ('RULE_OUT', 'Rule Out')], default='ACTIVE', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical')], max_length=20, null=True)),
                ('onset_date', models.DateField(default=django.utils.timezone.now, help_text='When symptoms first appeared')),
                ('date_diagnosed', models.DateTimeField(auto_now_add=True)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('is_chronic', models.BooleanField(default=False)),
                ('is_congenital', models.BooleanField(default=False)),
                ('clinical_findings', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='api.appointment')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='api.child')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_made', to='api.doctorprofile')),
                ('history', models.ManyToManyField(blank=True, related_name='related_diagnoses', to='api.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='diagnoses/attachments/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.diagnosis')),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'nurse', 'pharmacist', 'lab_tech']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_at_prescription', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg at time of prescription', max_digits=5, null=True)),
                ('date_prescribed', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_received', to='api.child')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to='api.diagnosis')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_given', to='api.doctorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('QD', 'Once daily'), ('BID', 'Twice daily'), ('TID', 'Three times daily'), ('QID', 'Four times daily'), ('Q4H', 'Every 4 hours'), ('Q6H', 'Every 6 hours'), ('Q8H', 'Every 8 hours'), ('Q12H', 'Every 12 hours'), ('PRN', 'As needed'), ('STAT', 'Immediately'), ('AC', 'Before meals'), ('PC', 'After meals'), ('HS', 'At bedtime')], max_length=5)),
                ('duration_value', models.PositiveIntegerField(default=1)),
                ('duration_unit', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='DAYS', max_length=6)),
                ('max_refills', models.PositiveIntegerField(default=0)),
                ('refills_used', models.PositiveIntegerField(default=0)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_weight_based', models.BooleanField(default=False)),
                ('dose_per_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('min_dose', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('max_dose', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='DrugDispenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.PositiveIntegerField()),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_dispensed', models.DateTimeField(auto_now_add=True)),
                ('dispensing_notes', models.TextField(blank=True, null=True)),
                ('is_refill', models.BooleanField(default=False)),
                ('pharmacist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_drugs', to='api.pharmacistprofile')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_records', to='api.prescriptionitem')),
            ],
        ),
        migrations.CreateModel(
            name='AdverseReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_description', models.TextField()),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('LIFE_THREATENING', 'Life-threatening')], max_length=20)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('actions_taken', models.TextField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_reactions', to='api.child')),
                ('reported_by', models.ForeignKey(limit_choices_to={'role__in': ['doctor', 'nurse', 'pharmacist', 'lab_tech']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_reactions', to='api.drug')),
                ('prescription_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.prescriptionitem')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.doctorprofile')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='api.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('MAJOR', 'Major'), ('CONTRAINDICATED', 'Contraindicated')], max_length=15)),
                ('description', models.TextField()),
                ('alternative_suggestion', models.TextField(blank=True, null=True)),
                ('drug_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_first', to='api.drug')),
                ('drug_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_second', to='api.drug')),
            ],
            options={
                'unique_together': {('drug_one', 'drug_two')},
            },
        ),
    ]
