# Generated by Django 5.1.7 on 2025-04-25 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_drug_diagnosis_diagnosisattachment_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='created_by',
        ),
    ]
