# Generated by Django 5.1.7 on 2025-04-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_treatment_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ['ward', 'bed_number']},
        ),
        migrations.RemoveField(
            model_name='ward',
            name='assigned_doctor',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='assigned_nurses',
        ),
        migrations.AddField(
            model_name='bed',
            name='last_cleaned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional information about the bed'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='available_beds',
            field=models.PositiveIntegerField(default=0, help_text='Number of currently available beds'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Total number of beds the ward can hold'),
        ),
    ]
