# Generated by Django 5.1.7 on 2025-04-27 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_bed_options_remove_ward_assigned_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionrecord',
            name='bed',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission', to='api.bed'),
        ),
    ]
