# Generated by Django 5.1.7 on 2025-05-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='is_administered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
