# Generated by Django 5.1.7 on 2025-05-09 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_vaccinationrecord_is_administered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='reports/')),
                ('report_type', models.CharField(choices=[('admission', 'Admission Report'), ('discharge', 'Discharge Report')], max_length=20)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_count', models.IntegerField(default=0)),
                ('emailed', models.BooleanField(default=False)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('users', models.ManyToManyField(related_name='accessible_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
