# Generated by Django 5.1.7 on 2025-05-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Test code (e.g., CBC, LFT)', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sample_type', models.CharField(choices=[('BLOOD', 'Blood'), ('URINE', 'Urine'), ('STOOL', 'Stool'), ('CSF', 'Cerebrospinal Fluid'), ('SWAB', 'Swab'), ('TISSUE', 'Tissue'), ('SPUTUM', 'Sputum'), ('OTHER', 'Other')], max_length=20)),
                ('sample_volume_required', models.CharField(blank=True, help_text="e.g., '2-3 mL' or '5 mL'", max_length=50, null=True)),
                ('preparation_instructions', models.TextField(blank=True, help_text='Patient preparation instructions', null=True)),
                ('collection_instructions', models.TextField(blank=True, help_text='Sample collection instructions', null=True)),
                ('processing_time', models.PositiveIntegerField(help_text='Estimated processing time in hours')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_fasting', models.BooleanField(default=False)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('minimum_age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('pediatric_considerations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
