# Generated by Django 5.1.7 on 2025-05-15 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_labtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('min_age_months', models.PositiveIntegerField(default=0)),
                ('max_age_months', models.PositiveIntegerField(default=216)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('ALL', 'All')], default='ALL', max_length=3)),
                ('min_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit', models.CharField(max_length=20)),
                ('textual_reference', models.CharField(blank=True, help_text='For qualitative tests without numeric ranges', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='api.labtest')),
            ],
            options={
                'unique_together': {('lab_test', 'parameter_name', 'min_age_months', 'max_age_months', 'gender')},
            },
        ),
    ]
