# Generated by Django 5.1.7 on 2025-05-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_referencerange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencerange',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
