# Generated by Django 5.1.7 on 2025-05-22 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_prescription_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionrecord',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.diagnosis'),
        ),
        migrations.AlterField(
            model_name='admissionrecord',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission', to='api.bed'),
        ),
    ]
