# Generated by Django 5.1.7 on 2025-05-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_admissionrecord_diagnosis_alter_admissionrecord_bed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionvitalrecord',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='admissionvitalrecordhistory',
            name='blood_pressure',
        ),
        migrations.AddField(
            model_name='admissionvitalrecord',
            name='diastolic',
            field=models.PositiveIntegerField(default=80, help_text='Diastolic pressure in mm Hg'),
        ),
        migrations.AddField(
            model_name='admissionvitalrecord',
            name='systolic',
            field=models.PositiveIntegerField(default=120, help_text='Systolic pressure in mm Hg'),
        ),
        migrations.AddField(
            model_name='admissionvitalrecordhistory',
            name='diastolic',
            field=models.PositiveIntegerField(default=80, help_text='Diastolic pressure in mm Hg'),
        ),
        migrations.AddField(
            model_name='admissionvitalrecordhistory',
            name='systolic',
            field=models.PositiveIntegerField(default=120, help_text='Systolic pressure in mm Hg'),
        ),
    ]
