# Generated by Django 5.1.7 on 2025-05-25 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_admissionvitalrecord_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionvitalrecordhistory',
            name='admission_vital_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.admissionvitalrecord'),
        ),
    ]
