# Generated by Django 5.1.7 on 2025-05-25 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_admissionvitalrecordhistory_admission_vital_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionvitalrecordhistory',
            name='admission_vital_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.admissionvitalrecord'),
        ),
    ]
