# Generated by Django 5.1.7 on 2025-05-31 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_admissionvitalrecordhistory_admission_vital_record'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referencerange',
            unique_together=set(),
        ),
    ]
