# Generated by Django 5.1.7 on 2025-05-31 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_referencerange_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referencerange',
            unique_together={('lab_test', 'parameter_name', 'min_age_months', 'max_age_months', 'gender')},
        ),
    ]
