# Generated by Django 5.1.7 on 2025-06-01 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_referencerange_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('SCHEDULED', 'Scheduled'), ('COLLECTED', 'Sample Collected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Results Complete'), ('VERIFIED', 'Results Verified'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Sample Rejected')], default='ORDERED', max_length=20)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'STAT (Immediate)')], default='ROUTINE', max_length=10)),
                ('request_id', models.CharField(max_length=20, unique=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('sample_collection_date', models.DateTimeField(blank=True, null=True)),
                ('results_date', models.DateTimeField(blank=True, null=True)),
                ('clinical_notes', models.TextField(blank=True, help_text='Clinical information relevant to test interpretation', null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_fasting', models.BooleanField(default=False)),
                ('is_billable', models.BooleanField(default=False)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='api.child')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to='api.diagnosis')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests_ordered', to='api.doctorprofile')),
                ('sample_collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_collected', to='api.labtechprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_verified', to='api.labtechprofile')),
            ],
        ),
    ]
