# Generated by Django 5.1.7 on 2025-06-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_labrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequest',
            name='request_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
