# Generated by Django 5.1.7 on 2025-06-01 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_alter_labrequest_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('lab_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_items', to='api.labrequest')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.labtest')),
            ],
            options={
                'unique_together': {('lab_request', 'lab_test')},
            },
        ),
    ]
