# Generated by Django 5.1.7 on 2025-06-02 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_labrequestitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_status', models.CharField(choices=[('NORMAL', 'Normal'), ('ABNORMAL', 'Abnormal'), ('CRITICAL', 'Critical'), ('INCONCLUSIVE', 'Inconclusive')], max_length=15)),
                ('date_performed', models.DateTimeField(auto_now_add=True)),
                ('date_verified', models.DateTimeField(blank=True, null=True)),
                ('report_notes', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('lab_request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.labrequestitem')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_performed', to='api.labtechprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_verified_items', to='api.labtechprofile')),
            ],
        ),
    ]
