# Generated by Django 5.1.7 on 2025-06-02 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_rename_result_status_labresult_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresult',
            name='status',
        ),
        migrations.CreateModel(
            name='LabResultParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('ABNORMAL', 'Abnormal'), ('CRITICAL', 'Critical'), ('INCONCLUSIVE', 'Inconclusive')], max_length=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lab_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.labresult')),
                ('reference_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.referencerange')),
            ],
        ),
    ]
