# Generated by Django 5.1.7 on 2025-06-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_remove_labresult_status_labresultparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresultparameter',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
