# Generated by Django 5.1.7 on 2025-06-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_labresultparameter_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='labresultparameter',
            unique_together={('lab_result', 'parameter_name')},
        ),
    ]
