# Generated by Django 5.1.7 on 2025-06-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_labresultparameter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresultparameter',
            name='status',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('ABNORMAL', 'Abnormal'), ('CRITICAL', 'Critical'), ('INCONCLUSIVE', 'Inconclusive')], max_length=15, null=True),
        ),
    ]
