# Generated by Django 5.1.7 on 2025-07-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_bill_billitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillItem',
        ),
    ]
