# Generated by Django 5.1.7 on 2025-07-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='GHC', max_length=10),
        ),
    ]
