# Generated by Django 5.1.7 on 2025-09-17 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_payment_options_payment_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations_received', to='api.child'),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='api.vaccine'),
        ),
    ]
