# Generated by Django 5.1.7 on 2025-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_summary_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
