# Generated by Django 5.1.7 on 2025-09-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_conversation_last_summary_at_conversation_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='last_summary_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='summary',
        ),
    ]
