# Generated by Django 5.1.7 on 2025-09-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_remove_conversation_last_summary_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
